### ISSUE TITLE
Resources > Pagination

### ISSUE THREAD

**Issue by anneguo3** [nwplus/www#11]
Add pagination for the resources - to be 6/page on desktop + 4/page on mobile
<img width="506" alt="Screen Shot 2021-08-04 at 7 04 32 PM" src="https://user-images.githubusercontent.com/40816838/128266463-192240b4-d421-4d7b-ba96-08e0d6225c76.png">
<img width="170" alt="Screen Shot 2021-08-04 at 7 04 41 PM" src="https://user-images.githubusercontent.com/40816838/128266476-496a0748-f318-46d0-8ccb-909b8678275e.png">

**Comment by panjenny0** [comment]
@anneguo3 is this for fetching + displaying the resources themselves, or just creating the layout for the resources cards (i.e. positioning the cards)?
Also FYI I'm going to tackle the pagination component separately in #53
