### ISSUE TITLE
Bug: Add in inactive state for "Live Portal" button

### ISSUE THREAD

**Issue by anneguo3** [nwplus/www#115]
Add inactive state for the "Live Portal" button in the navbar with: 
text is `#FFFFFF 60%`
button is `background: rgba(255, 255, 255, 0.6);
opacity: 0.6;
border-radius: 34px;`

**Comment by kevin-zou** [comment]
I just hardcoded this in #119, think it's fine for the time being. Can change this to read from CMS eventually but will close this for now!
