### ISSUE TITLE
Bug: newsletter email field doesn’t clear after subscribing

### ISSUE THREAD

**Issue by shuting-hu** [nwplus/www#120]
the newsletter email field doesn't clear email after hitting subscribe (more visual indication that email has been submitted)

**Comment by kevin-zou** [comment]
Does #121 close this @shuting-hu? On successful submit it clears info/error messages and closes the modal. This was already pushed to live so you can check the behaviour right now!

**Comment by shuting-hu** [comment]
@kevin-zou that works too, thanks!!
