### ISSUE TITLE
Application Page

### ISSUE THREAD

**Issue by anneguo3** [nwplus/www#17]
Application page

Buttons should have a "turned off" state -> makes them unclickable

<img width="729" alt="Screen Shot 2021-07-15 at 11 10 26 PM" src="https://user-images.githubusercontent.com/40816838/125885848-5c113e63-2419-431b-9460-9d01cda9e2af.png">

**Comment by phoenixthefirebird** [comment]
waiting for the button component to merge

**Comment by kevin-zou** [comment]
Well looks like linking an issue after the PR has been merged doesn't work. Anyways, this was closed by the above PR!
