### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by anneguo3** [nwplus/www#3]
Add the navbar - with Hackathons being a drop down to all three hackathons, and a router for "Join the Team" and Live Portal links and set-up dummy holders for "About Us" and "Resources"
<img width="461" alt="Screen Shot 2021-07-15 at 10 32 46 PM" src="https://user-images.githubusercontent.com/40816838/125882721-810c07ca-73d3-4f1a-82bc-309fd8823b51.png">

**Comment by phoenixthefirebird** [comment]
![image](https://user-images.githubusercontent.com/55338489/128606875-33afeb8e-2bcf-4714-b76b-611cc06ec70a.png)
this is the most updated version of navbar on figma
