### ISSUE TITLE
CMS Connection > Database Schema

### ISSUE THREAD

**Issue by anneguo3** [nwplus/www#33]
Create new database schema to store all nwPlus site content

Editable content:
- Hackathons (open/close & hackathon URL)
- Resources (add/delete/update)
- FAQ (add/delete/update)
- Applications (open/close & URL & date)

**Comment by phoenixthefirebird** [comment]
we also need application deadline as seen here: 
![image](https://user-images.githubusercontent.com/55338489/128641229-c9abb85e-7e72-4f91-a9e9-ce03592e8c04.png)

**Comment by kozr** [comment]
You can worry about this last

**Comment by kozr** [comment]
that means after Friday if you're busy with other stuff

**Comment by phoenixthefirebird** [comment]
I see thanks for letting me know! Still want to make sure the firebase db object works tho xd
