### ISSUE TITLE
CMS Connection > Make updates to the CMS UI update nwPlus website

### ISSUE THREAD

**Issue by anneguo3** [nwplus/www#36]
Create a new website under the "Websites" section of CMS 
<img width="284" alt="Screen Shot 2021-08-04 at 7 01 45 PM" src="https://user-images.githubusercontent.com/40816838/128266256-ded79170-4aac-42d7-bb6d-27caf3ffdd02.png">

**Comment by kozr** [comment]
done 
![image](https://user-images.githubusercontent.com/40312631/130371107-29d5bae5-bc71-470b-8de7-8c3f6530b428.png)
