### ISSUE TITLE
Who We Are/What We Do Section Toggle

### ISSUE THREAD

**Issue by anneguo3** [nwplus/www#5]
Who We Are / What We Do section switch, add containers for both sections, add the string for the "Who We Are" section

<img width="461" alt="Screen Shot 2021-07-15 at 10 41 05 PM" src="https://user-images.githubusercontent.com/40816838/125883461-0982c6f3-849c-4a2b-a46c-eb9abe5c7c64.png">

**Comment by kevin-zou** [comment]
Closed by the mentioned PR
