### ISSUE TITLE
Nit: decouple lines with noise for background

### ISSUE THREAD

**Issue by panjenny0** [nwplus/www#68]

**Comment by anneguo3** [comment]
@panjenny0 can you add additional details on this ticket?

**Comment by panjenny0** [comment]
Additional details:
- this was needed because initially, I exported the background lines and the noise texture together as one svg when I worked on the site background. But later on, we realized that the application page needed the background noise texture but not the lines. 
- I think this was already addressed by @phoenixthefirebird but @anneguo3 I'll assign to myself and take a look just to be sure 👀 
- @andykwan1124 mind if we trade tickets? ie if I take this, can you work on the resource card responsiveness? I think Vincent already worked on it but might need to double check - in any case, it would be super quick (minimal work)

**Comment by anneguo3** [comment]
@phoenixthefirebird can you double check if Jenny's comment is true that it was complete as a result of your work?

**Comment by phoenixthefirebird** [comment]
indeed! Feel free to close it:)
