### ISSUE TITLE
Make Hackathon Cards mobile responsive

### ISSUE THREAD

**Issue by panjenny0** [nwplus/www#70]
Current
<img width="496" alt="Screen Shot 2021-08-26 at 11 38 56 AM" src="https://user-images.githubusercontent.com/38872354/131018015-4f422b7f-33fc-46c8-a2ea-5c671dd541c6.png">
What it needs to be
<img width="493" alt="Screen Shot 2021-08-26 at 11 39 34 AM" src="https://user-images.githubusercontent.com/38872354/131018033-e26f54ad-738e-43c3-a2e0-46352fd0619a.png">

**Comment by vincentchiang1** [comment]
@panjenny0 @anneguo3 has this been resolved? I tried a couple mobile screen sizes and they look fine to me 
![image](https://user-images.githubusercontent.com/37602670/132963206-a088f98d-e738-4078-857a-2c16b9792ca9.png)

**Comment by panjenny0** [comment]
> @panjenny0 @anneguo3 has this been resolved? I tried a couple mobile screen sizes and they look fine to me
> ![image](https://user-images.githubusercontent.com/37602670/132963206-a088f98d-e738-4078-857a-2c16b9792ca9.png)

Yep I think this should be resolved! Just checked too and it looks good. Closing this ticket 🎟️
