### ISSUE TITLE
Mobile bug: odd white margin on the right side of the site

### ISSUE THREAD

**Issue by panjenny0** [nwplus/www#89]
Not sure what introduced this but worth looking into 
![image](https://user-images.githubusercontent.com/38872354/131301077-78f8cc1f-3e9a-4d95-b614-5892c05bffd3.png)

**Comment by anneguo3** [comment]
Probable cause: Image in the "Who We Are" section - assigning to @dchen150 given he worked on that

**Comment by panjenny0** [comment]
Could also be caused by carousel
<img width="231" alt="Screen Shot 2021-09-11 at 12 23 58 PM" src="https://user-images.githubusercontent.com/38872354/132959220-353cb881-8dc7-4f59-87cf-d3096cf57621.png">
(noticed this while looking at #98)

**Comment by kevin-zou** [comment]
Talked to Derek, taking this one for now as he's already got others!

**Comment by anneguo3** [comment]
@kevin-zou I was looking at the live version and I think Jenny's comment is right in saying that this bug is caused by the photo carousel because it still exists 😭

**Comment by kevin-zou** [comment]
Oops, I will work on a fix for that right now!
