### ISSUE TITLE
Resources > Resource Card

### ISSUE THREAD

**Issue by anneguo3** [nwplus/www#9]
Resource Card with:
- logo of the location of the resource (YouTube/Medium/GitHub/Powerpoint) icon can be found on Figma
- Title
- Event | Year
- Toggle for "Our Pick" with a icon on the image
<img width="327" alt="Screen Shot 2021-08-04 at 6 53 28 PM" src="https://user-images.githubusercontent.com/40816838/128265606-d86dac0f-f975-4655-80b0-f53e8eab9edc.png">
- on hover should make the logo of the location disappear
<img width="847" alt="Screen Shot 2021-08-04 at 6 53 53 PM" src="https://user-images.githubusercontent.com/40816838/128265643-56f76a4c-28dd-4ce6-a6bd-4b8e3f039f0f.png">

<img width="787" alt="Screen Shot 2021-08-04 at 6 54 31 PM" src="https://user-images.githubusercontent.com/40816838/128265709-2d66468d-24aa-4881-baf0-7a6087e55bc3.png">

**Comment by kevin-zou** [comment]
Closing as this has already been done!
